"""Build Velkio Dock's standalone, inline-styled Odoo Apps description and native icon."""
from pathlib import Path
from html import escape
import shutil
from PIL import Image, ImageDraw
ROOT=Path(__file__).resolve().parents[1]
OUT=ROOT/'velkio_odoo_dock/static/description'

def picture(src,alt):
    return f'<img src="{src}" alt="{escape(alt)}" style="max-width:100%;width:100%;height:auto;display:block;border-radius:12px;">'
def heading(label,title):
    return f'<p style="color:#9A7135;font-size:12px;letter-spacing:2px;font-weight:700;">{label.upper()}</p><h2 style="font-size:29px;line-height:1.25;margin:8px 0 24px;color:#282532;">{title}</h2>'
def cards(items):
    return '<div class="row" style="display:flex;flex-wrap:wrap;gap:16px;">'+''.join(f'<article style="box-sizing:border-box;flex:1 1 280px;min-width:0;padding:24px;border:1px solid #E6DFE8;border-radius:12px;background:#fff;"><span style="color:#9A7135;font-weight:700;">{i:02d}</span><h3 style="font-size:20px;color:#714B67;margin:12px 0;">{escape(t)}</h3><p style="margin:0;color:#625F6C;">{escape(b)}</p></article>' for i,(t,b) in enumerate(items,1))+'</div>'
def section(id,label,title,body,tint=False):
    return f'<section id="{id}" style="padding:28px 24px;margin:24px 0;background:{"#F6F1F6" if tint else "#FFFFFF"};border-radius:14px;">{heading(label,title)}{body}</section>'
features=[('Your personal dock','Pin the apps you use, reorder them by dragging and keep your preferences saved per user.'),('Four positions, six styles','Left, right, top or bottom. Choose Dark, Floating, Glass, Light, Odoo Purple or Accent Colour.'),('Find apps and records','Search apps, available menus and recent records from the Show Applications overview.'),('A welcoming home','On Enterprise desktop: your company logo, a live clock, a greeting with your name, and recent work.'),('Recent apps and favourite menus','Keep recently used apps and starred menus close. Open recent records from the workspace or overview.'),('Useful navigation extras','Optional badges for supported apps, magnification, auto-hide, keyboard shortcuts and new-tab actions.')]
setup=[('Install the module','Add velkio_odoo_dock to your Odoo 19 addons path. Restart Odoo, update the Apps list and install Velkio Odoo Dock.'),('Choose your apps','Click the dock’s + button, select your everyday apps, and drag pinned icons into your preferred order.'),('Style your dock','Open Dock Settings. Choose Appearance and Behaviour options, preview changes live, then click Save changes.'),('Add your company logo','Set the logo in Odoo company settings. The Enterprise home workspace uses the active company’s logo.'),('Return to your work','Open an app from the dock. Use Show Applications to find other apps, menus and recent records.'),('Upgrade an existing installation','Restart Odoo, upgrade the module and hard-refresh the browser to load new assets. Preferences remain personal.')]
workflow=[('Start at home','On Enterprise desktop, see the company logo, live date/time and a greeting in Odoo’s colour scheme.'),('Open an app','Choose a pinned app from the dock or search from the application overview.'),('Keep important menus nearby','Star a menu from overview search to add it to your favourite menus.'),('Pick up where you left off','Return home for recent records and recent apps, or use the overview while working.')]
faq=[('Community or Enterprise?','The dock works with the Odoo 19 backend in both editions. The welcome workspace replaces the Enterprise desktop home app grid; Community retains its normal navigation.'),('Is the dock user-wise?','Yes. Pins, preferences, favourite menus and recent history are saved for each user. There is no administrator group-default screen.'),('What happens on phones?','The dock and custom home workspace are hidden below 768px. Odoo’s normal mobile home navigation remains available.'),('Does it grant extra access?','No. Returned menus respect Odoo visibility rules, and recent records are checked against the current user’s read access.'),('Which badges are available?','Unread Discuss messages and supported due To-dos/activities when the relevant apps are installed. Badge display is optional.'),('Which shortcuts can I use?','Alt+Shift+O opens the overview. Alt+Shift+1 through 9 open pinned apps. Shortcuts can be disabled in settings.')]
shots=[('screenshot_workspace_light.png','Your company, your workspace','The Enterprise home workspace in light mode, using the Velkio company logo.'),('screenshot_workspace_dark.png','Comfortable in dark mode','The same personal workspace with a live clock and time-based greeting.'),('screenshot_overview.png','All your apps, one overview','Browse apps and recent work from the dock without restoring the default home grid.'),('screenshot_search.png','Search apps and menus','Find accessible apps, menus and recent records from one search field.'),('screenshot_appearance.png','Choose your appearance','Four positions, six styles, icon size, accent colour and overview theme.'),('screenshot_behaviour.png','Control how your dock behaves','Auto-hide, magnification, badges, favourites, shortcuts and history controls.'),('screenshot_pin_apps.png','Pin the apps you use','Pick your everyday apps and keep your dock personal.')]
html='<section class="oe_container" style="box-sizing:border-box;max-width:1320px;width:100%;margin:0 auto;font-family:Arial,Helvetica,sans-serif;line-height:1.6;color:#282532;background:#fff;padding:16px;">'
html+='<header style="display:flex;align-items:center;justify-content:space-between;flex-wrap:wrap;gap:20px;padding:16px 24px;">'+ '<img src="velkio_logo.png" alt="Velkio Odoo Solutions Precision logo" style="max-width:100%;width:150px;height:auto;">'+ '<span style="color:#714B67;font-size:13px;font-weight:700;">Odoo 19 · Community &amp; Enterprise · LGPL-3</span></header>'
html+=picture('banner.png','Velkio Odoo Dock marketing banner — personal dock, search and recent work')
html+=section('overview','Overview','Velkio Odoo Dock','<h1 style="font-size:38px;line-height:1.2;margin:0 0 16px;">Your apps. Your workspace. Your way.</h1><p style="font-size:18px;color:#625F6C;">A personal dock for Odoo’s backend, with pinned apps, useful search and a welcoming Enterprise home workspace. Choose how it looks and keep recent work within reach.</p><div style="display:flex;flex-wrap:wrap;gap:12px;">'+''.join(f'<a href="#{x}" style="display:inline-block;padding:10px 18px;color:#714B67;border:1px solid #DCCEDD;border-radius:8px;text-decoration:none;font-weight:700;">{y}</a>' for x,y in [('features','Features'),('setup','Setup'),('workflow','Workflow'),('screenshots','Screenshots'),('video','Video'),('faq','FAQ')])+'</div>',True)
html+=section('features','Features','A dock that fits the way you work',cards(features))
html+=section('setup','Setup','Ready in a few clear steps',cards(setup),True)
html+=section('workflow','Daily workflow','From finding an app to continuing your work',cards(workflow))
html+=section('screenshots','Real product screenshots','See the controls you will actually use',''.join(f'<figure style="margin:0 0 32px;padding:20px;border:1px solid #E6DFE8;border-radius:14px;background:#fff;"><h3 style="font-size:21px;color:#714B67;margin:0 0 8px;">{title}</h3><p style="color:#625F6C;margin:0 0 18px;">{desc}</p>{picture(file,title)}<figcaption style="font-size:12px;color:#625F6C;margin-top:12px;">Captured from the VELKIO Odoo 19 Enterprise database. App availability depends on your installation and permissions.</figcaption></figure>' for file,title,desc in shots),True)
html+=section('video','Video walkthrough','Take a short tour','<video controls preload="metadata" playsinline src="demo.webm" poster="screenshot_workspace_dark.png" aria-label="Velkio Dock video walkthrough" style="max-width:100%;width:100%;height:auto;display:block;border-radius:12px;background:#18131f;">Your browser does not support this video.</video>'+'<p style="margin-top:20px;">A captioned video using the real VELKIO screenshots: welcome workspace, search, appearance, behaviour and app pinning.</p><a href="/velkio_odoo_dock/static/description/demo.webm" style="display:inline-block;background:#714B67;color:#fff;padding:12px 24px;border-radius:8px;text-decoration:none;font-weight:700;">Watch or download the walkthrough (.webm)</a><p style="font-size:12px;color:#625F6C;">The video is included in the module package. For an externally hosted Apps listing video, publish this file and add your real video URL.</p>')
html+=section('faq','FAQ','Know what is included',cards(faq),True)
html+='<footer style="padding:28px;text-align:center;border-top:1px solid #E6DFE8;color:#714B67;"><strong>VELKIO · ODOO SOLUTIONS</strong><p>Designed for personal navigation in Odoo 19.</p></footer></section>'
(OUT/'index.html').write_text(html)
# Native, editable app icon: a screen with a floating app dock, no company logo.
svg='''<svg xmlns="http://www.w3.org/2000/svg" width="512" height="512" viewBox="0 0 512 512"><rect width="512" height="512" rx="112" fill="#714b67"/><rect x="74" y="98" width="364" height="254" rx="32" fill="#f3edf5"/><rect x="96" y="120" width="320" height="208" rx="18" fill="#ddd2e3"/><rect x="184" y="374" width="144" height="24" rx="12" fill="#f3edf5"/><rect x="238" y="346" width="36" height="40" fill="#f3edf5"/><rect x="127" y="224" width="258" height="78" rx="26" fill="#302236"/><rect x="146" y="241" width="44" height="44" rx="12" fill="#f8b54d"/><rect x="204" y="241" width="44" height="44" rx="12" fill="#16c7b6"/><rect x="262" y="241" width="44" height="44" rx="12" fill="#e77399"/><rect x="320" y="241" width="44" height="44" rx="12" fill="#70aaf4"/><circle cx="121" cy="147" r="6" fill="#714b67"/><rect x="143" y="141" width="160" height="12" rx="6" fill="#b6a4bf"/></svg>'''
(OUT/'icon.svg').write_text(svg)
im=Image.new('RGBA',(512,512));d=ImageDraw.Draw(im)
for box,r,c in [((0,0,512,512),112,'#714b67'),((74,98,438,352),32,'#f3edf5'),((96,120,416,328),18,'#ddd2e3'),((184,374,328,398),12,'#f3edf5')]: d.rounded_rectangle(box,r,fill=c)
d.rectangle((238,346,274,386),fill='#f3edf5');d.rounded_rectangle((127,224,385,302),26,fill='#302236')
for x,c in [(146,'#f8b54d'),(204,'#16c7b6'),(262,'#e77399'),(320,'#70aaf4')]: d.rounded_rectangle((x,241,x+44,285),12,fill=c)
d.ellipse((115,141,127,153),fill='#714b67');d.rounded_rectangle((143,141,303,153),6,fill='#b6a4bf');im.save(OUT/'icon.png')
print('Built index and dock app icon')
