"""Store-page copy checked against the connector models and views."""
COMMON = {
    'publisher': 'Velkio Odoo Solutions',
    'email': 'velkio.odoosolution@gmail.com',
    'hosting': 'Odoo 19 on Odoo.sh or on-premise, with custom Python add-ons enabled. Standard Odoo Online does not support these modules.',
}
APPS = {
    'woo': {
        'module': 'velkio_woocommerce_connector',
        'name': 'Velkio WooCommerce Connector',
        'edition': 'Odoo 19 · Community & Enterprise',
        'license': 'OPL-1', 'version': '19.0.1.0.1',
        'accent': '#714B67', 'tint': '#F6F1F6',
        'headline': 'Your store and Odoo. One clear workflow.',
        'intro': 'Bring WooCommerce products, customers and sales orders into Odoo. Update mapped store products from Odoo, manage multiple connections and review your synchronization activity in one workspace.',
        'chips': ['Multiple stores', 'Product import & export', 'Customer & order imports'],
        'features': [
            ('One workspace for your stores', 'Keep separate API credentials, company, warehouse and pricelist defaults for each WooCommerce connection.'),
            ('Product data in both directions', 'Import product names, SKUs and prices. Export the name, SKU and regular price of mapped Odoo products.'),
            ('Customer records in Odoo', 'Import customer names, email addresses and phone numbers, then review their store-to-Odoo mappings.'),
            ('Store orders become sales orders', 'Import new orders with product lines, quantities and prices. Choose whether to confirm imported sales orders automatically.'),
            ('Record links you can inspect', 'Open product, customer and order mappings to see which WooCommerce record corresponds to each Odoo record.'),
            ('Dashboard and operation history', 'Review connected stores, synchronization activity and operation results. Run import and export actions from Odoo.'),
        ],
        'sync': [
            ('Products', 'WooCommerce ↔ Odoo', 'Names, SKUs and prices; export operates on product mappings.'),
            ('Customers', 'WooCommerce → Odoo', 'Names, email addresses and phone numbers.'),
            ('Sales orders', 'WooCommerce → Odoo', 'New sales orders and product lines. Already mapped orders are skipped.'),
        ],
        'scope': 'Synchronization is action-based. Sync All imports products, customers and orders; product export is a separate action. This release does not provide scheduled sync, webhooks, stock-quantity sync, image sync, variation sync, refund sync or order-status updates back to WooCommerce. Shipping charges, discounts and tax-line mapping are not included in the order import.',
        'requirements': [
            'An Odoo 19 environment with Sales and Inventory. Required Odoo dependencies are installed with the module.',
            'A WooCommerce store reachable from the Odoo server, preferably over HTTPS.',
            'A WooCommerce REST API key with Read/Write access, associated with a user allowed to access the required store data.',
            'WordPress permalinks set to an option other than Plain. WooCommerce uses the wc/v3 REST API for this connector.',
        ],
        'steps': [
            ('Install the connector', 'Add the module to your custom add-ons, update the Apps list and install WooCommerce Connector. Open WooCommerce from the app menu.'),
            ('Create your store API keys', 'In WordPress, go to WooCommerce → Settings → Advanced → REST API → Add Key. Choose Read/Write permission and generate the key. Save the Consumer Key and Consumer Secret securely.'),
            ('Add an Odoo connection', 'Open WooCommerce → Instances → New. Enter a name, Store URL, Consumer Key and Consumer Secret. Select the company, warehouse and pricelist. Leave automatic order confirmation off while checking your first import.'),
            ('Test the connection', 'Save the instance and select Test Connection. If it fails, check the store URL, API permissions and whether the Odoo server can reach the store.'),
            ('Import your first records', 'Select Import Products, then Import Customers, then Import Orders. Review the new Odoo records and their mappings. Sync All runs these three imports together.'),
            ('Export and review', 'Check Product Mappings before selecting Export Products. Open Sync Logs to review completed actions and the dashboard for activity across stores.'),
        ],
        'workflow': [
            ('CONNECT', 'Store URL + API keys', 'Test the connection before importing.'),
            ('IMPORT', 'Products → Customers → Orders', 'Review the records created in Odoo.'),
            ('EXPORT', 'Mapped product updates', 'Run Export Products when you are ready.'),
            ('REVIEW', 'Mappings + Sync Logs', 'Check what ran and resolve any errors.'),
        ],
        'screenshots': [],
        'workspace': [
            ('Dashboard', 'See store counts, mapped records, activity charts and recent logs. Run actions for one store or all active stores.'),
            ('Instances', 'Maintain each store’s credentials and Odoo defaults. Test the connection and run individual import/export actions.'),
            ('Operations → Mappings', 'Inspect Product Mappings, Customer Mappings and Order Mappings before repeating an operation.'),
            ('Sync Logs', 'Read recorded operation results. If an action stops with an error, review that error before retrying.'),
        ],
        'faqs': [
            ('Does it synchronize automatically?', 'No. This release uses manual actions in Odoo. Sync All runs product, customer and order imports; it does not export products.'),
            ('Can I connect more than one store?', 'Yes. Create a separate instance for each store, with its own credentials and Odoo defaults.'),
            ('Can I export every Odoo product?', 'Exports use the selected instance’s Product Mappings. Review or create the mappings for the products you intend to export.'),
            ('Will repeat imports duplicate orders?', 'Orders already linked by a mapping for that instance are skipped. This also means later changes to an already imported order are not re-applied.'),
            ('Is there an import size limit?', 'Each action reads up to 10 pages of 100 records per resource. Catalogs or order histories above 1,000 records need an extended import strategy; this release does not include a historical migration tool.'),
            ('What data leaves Odoo?', 'Export Products sends mapped product names, SKUs and prices to your configured WooCommerce store. Imports retrieve store products, customers and orders. Connections use the credentials you configure.'),
        ],
        'troubleshooting': [
            ('Connection fails', 'Check the URL, REST API keys, Read/Write permission, WordPress permalinks and server network access.'),
            ('A product is not exported', 'Check that it has a Product Mapping for the correct instance, and review its name, SKU and price.'),
            ('An imported order does not change', 'Already mapped orders are skipped. Review the original Odoo order and its mapping.'),
        ],
    },
    'tally': {
        'module': 'velkio_tally_integration',
        'name': 'Velkio TallyPrime Connector',
        'edition': 'Odoo 19 · Community & Enterprise',
        'license': 'LGPL-3', 'version': '19.0.1.2.1',
        'accent': '#714B67', 'tint': '#F8F5EF',
        'headline': 'Connected accounting, with control over every flow.',
        'intro': 'Connect Odoo and TallyPrime for accounting and inventory synchronization. Choose which system owns each record type, follow outgoing records through a queue and review results inside Odoo.',
        'chips': ['Masters & transactions', 'Direction per record type', 'Queue & monitoring'],
        'features': [
            ('Choose the direction', 'Set Tally → Odoo, Odoo → Tally or two-way synchronization for supported record types, with a defined source of truth.'),
            ('Connect your master data', 'Work with account groups, general ledgers, parties, units, stock groups, stock items, locations, cost centres, taxes and currencies.'),
            ('Bring transactions together', 'Connect sales invoices, credit notes, purchase bills, debit notes, receipts, payments, journal and contra vouchers, and stock transfers.'),
            ('Start with the right accounts', 'Use onboarding to import the chart of accounts or map to an existing Odoo chart. Review opening balances and the history start date.'),
            ('Follow every outgoing record', 'Use the outbound queue, identity mappings and directional logs to see what was sent, received or needs attention.'),
            ('Run and monitor synchronization', 'Use Sync Now in direct mode. Scheduled processing handles queued changes, with automatic imports controlled by your instance settings.'),
        ],
        'sync': [
            ('Accounting masters', 'Configured per entity', 'Account groups, general ledgers, customers/vendors, taxes and currencies.'),
            ('Inventory masters', 'Configured per entity', 'Units, stock groups, stock items, godowns/locations and cost centres.'),
            ('Invoices and bills', 'Configured per entity', 'Sales, purchases, credit notes and debit notes.'),
            ('Payments and journals', 'Configured per entity', 'Receipts, payments, journal and contra vouchers.'),
            ('Stock transfers', 'Configured per entity', 'Stock journal / internal transfer records.'),
            ('Opening balances', 'Onboarding settings', 'Review chart mappings and opening-date settings before migration.'),
        ],
        'scope': 'Actual processing depends on the enabled record types, direction, ownership, account mappings and connection settings. Direct mode requires a reachable TallyPrime XML gateway. Agent mode requires a separately deployed on-premise relay; an agent executable is not bundled in this module.',
        'requirements': [
            'Odoo 19 with Accounting/Invoicing, Inventory and the module’s listed dependencies.',
            'A working TallyPrime installation and company, with the XML gateway enabled. The default configured port is 9000.',
            'A network route from the Odoo server to the TallyPrime host for direct mode. On Odoo.sh, localhost refers to the cloud server, not your office PC.',
            'Tally access rights in Odoo for users, and manager rights for configuration and synchronization controls.',
        ],
        'steps': [
            ('Prepare TallyPrime', 'Start TallyPrime, open the correct company and enable its XML gateway. Confirm the configured port is available. Keep TallyPrime at the Gateway screen while synchronizing.'),
            ('Install and grant access', 'Install TallyPrime Connector in Odoo. Give operators Tally user access and configuration owners Tally manager access.'),
            ('Create the connection', 'Open Tally Prime → Dashboard & Instances → New. Set the Odoo company, Tally host, port, protocol and Tally company. Use Direct mode when Odoo can reach the gateway.'),
            ('Test and complete onboarding', 'Select Test Connection. In Setup & Tools, review company discovery and onboarding. Choose whether to import the chart of accounts or map to an existing chart, and set the required history and opening settings.'),
            ('Choose ownership and direction', 'Review Sync Rules and What Syncs. Enable only the record types you need and decide which system wins when both systems change a record.'),
            ('Synchronize and inspect results', 'Start with Get Masters Only and verify mappings. Then use Sync Now for the configured flow. Review Odoo → Tally, Tally → Odoo, Waiting, Failed and All Logs. Configure automatic imports after validating the first run.'),
        ],
        'workflow': [
            ('PREPARE', 'Company + XML gateway', 'Confirm Odoo can reach TallyPrime.'),
            ('CONFIGURE', 'Accounts + record ownership', 'Set direction for each enabled entity.'),
            ('SYNCHRONIZE', 'Queue → send / import', 'Run manually or through configured schedules.'),
            ('REVIEW', 'Logs + linked records', 'Resolve failed or quarantined records.'),
        ],
        'screenshots': [
            ('01_dashboard.jpg', '01 · See the connection overview', 'Review instance status and synchronization counts from Dashboard & Instances.'),
            ('02_connection.jpg', '02 · Configure and test the connection', 'Set the gateway host and port, then check the connection before importing data.'),
            ('03_what_syncs.jpg', '03 · Decide what syncs', 'Review enabled entities, direction and the source of truth for each record type.'),
            ('04_invoice_tally_post.jpg', '04 · Send an invoice from Odoo', 'Use the Tally Post action on a supported invoice and review its integration status.'),
            ('05_posted_to_tally.jpg', '05 · Review outgoing results', 'Inspect the record, direction, outcome and related Odoo document.'),
            ('07_outbound_queue.jpg', '06 · Follow the outbound queue', 'Review queued records, attempts and processing state to find items that need attention.'),
        ],
        'faqs': [
            ('Is TallyPrime included?', 'No. This is an Odoo connector. You need your own working TallyPrime installation and an accessible XML gateway.'),
            ('Does it work with Odoo.sh?', 'The module can be deployed on Odoo.sh. Direct mode still needs a reachable TallyPrime endpoint. An office-only address or localhost will not connect a cloud server to your PC.'),
            ('Do I need an agent?', 'Direct mode connects from Odoo to TallyPrime without an agent. Agent mode is available for a separately deployed relay; the relay executable is not included in this add-on.'),
            ('How often does automatic sync run?', 'The direct-sync scheduled action is configured for every two minutes. Automatic pulls also depend on the instance’s automatic-import setting and pull interval. Actual timing depends on the Odoo scheduler and gateway availability.'),
            ('Which system wins when both records change?', 'The entity’s source-of-truth and direction settings control processing. Review these settings before enabling two-way synchronization.'),
            ('What happens to failed records?', 'Outgoing records can be reviewed in the queue and logs. Repeated inbound failures can enter quarantine, where an operator can review and retry them.'),
            ('What data is exchanged?', 'Enabled accounting, party, inventory and transaction records are exchanged with your configured TallyPrime endpoint according to their direction settings. Agent mode routes this traffic through your separately configured relay.'),
        ],
        'troubleshooting': [
            ('Connection is offline', 'Check that TallyPrime is running with the correct company open, the XML gateway is enabled and the host/port is reachable from Odoo.'),
            ('A record does not synchronize', 'Check whether its record type is enabled, its direction is correct, and its accounts and identity mappings are configured.'),
            ('A record is waiting or failed', 'Open Outbound Queue and Sync Logs, resolve the reported issue and retry. Review Inbound Quarantine for repeated import failures.'),
        ],
    },
}
