# -*- coding: utf-8 -*-
from . import constants
from . import res_company
from . import res_config_settings
from . import tally_account_type_map
from . import tally_instance
from . import tally_entity_config
from . import tally_mapping
from . import tally_sync_log
from . import tally_sync_queue
from . import tally_inbound_dead_letter
from . import tally_discovered_company
from . import account_move
from . import account_payment
from . import res_partner
from . import product_template
from . import account_account
from . import master_outbound
from . import stock_picking
from . import tally_manual_push
